import "./../styles/app.scss";
import type { Metadata } from "next";

import { GoogleAnalytics } from "nextjs-google-analytics";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme="monotone-dark">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="anonymous"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Hind+Vadodara:wght@300;400;500;600;700&family=Roboto+Mono:wght@700&family=Quattrocento+Sans:wght@700&display=swap"
                    // href="https://fonts.googleapis.com/css2?family=Hind+Vadodara:wght@300;400;500;600;700&family=Montserrat:wght@700&family=Quattrocento+Sans:wght@700&display=swap"
                    rel="stylesheet"
                />

                {/* Icons */}
                {/* <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        /> */}

                {/* Other */}
                {/* <link rel="manifest" href="/site.webmanifest" /> */}
                <meta name="theme-color" content="#272727" />
                <meta name="apple-mobile-web-app-capable" content="yes" />
            </head>

            {process && process.env.NODE_ENV === "production" && (
                <GoogleAnalytics strategy="lazyOnload" />
            )}

            <body>{children}</body>
        </html>
    );
}
